### ISSUE TITLE
Switch build system to XMake?

### ISSUE THREAD

**Issue by dargueta** [q66/cffi-lua#30]
Right now I can't install this via LuaRocks because Meson isn't installed on our systems. Furthermore, adding cffi-lua as a dependency makes Meson a transitive dependency for building my library.

I was wondering if it'd be possible to switch over to using [xmake](https://xmake.io/) as the build system? It'll provide a number of advantages:

* There's a [LuaRocks plugin](https://luarocks.org/modules/waruqi/luarocks-build-xmake) you can add as a *build-time dependency* that'll automatically install it if it's not available. This means that users don't need to install XMake themselves.
* XMake's configuration is literally just plain Lua.
* You can use XMake's package management to install libffi if it's not installed already.
* XMake is cross-platform.

This means that all users need to install cffi-lua is some version of Lua, an appropriate C++ compiler, and either XMake or LuaRocks depending on how they're installing it.

**Comment by q66** [comment]
i don't have any plans to switch build systems, sorry; i generally don't use luarocks either, it's provided pretty much as a supplementary thing, the primary way is to just use meson

meson is also portable/cross-platform, there shouldn't be any reason you can't install it
