### ISSUE TITLE
Problem with simple "typedef" 

### ISSUE THREAD

**Issue by stustd** [q66/cffi-lua#40]
When copying from a LuaJit.FFI interface, in order to get the CFFI version working I had to remove simple typedefs like
```
typedef long type_t;
```
and use the `long` instead. This is the CFFI error msg I get with typedef declarations:
```
input:1: ';' expected near 'time_t'
```
Any hope this can be integrated with CFFI? (... or am I doing something wrong; couldn't find an example or test using it.)

**Comment by q66** [comment]
i realized that tests for this were missing, so i added some in the referenced commit, but it seems to be working fine?

**Comment by q66** [comment]
It seems luajit allows you to redefine "builtin" typedefs (even though it doesn't do anything). I changed the behavior to allow the same, but I'd advise you not to redefine them

**Comment by amsitlab** [comment]
I still getting error like this. btw I use latest version from luajit.

**Comment by q66** [comment]
the fix is only present in git master, the release is older

i should probably tag a new one soonish...
